remote_theme: tuur29/pages-themes-cayman
show_downloads: true
title: Alright Launcher Website
description: Yet Another Minecraft Launcher Using C# 
darkmode: true 
syntax_theme: ./syntax.css # Leave empty for default, otherwise link to a pygments stylesheet
logo_url: https://github.com/batuhantrkgl/alrightlauncher/blob/gh-pages/logo.png # Either absolute or relative url
color:
  header: "#000"
  gradient_left: "#e53935"
  gradient_right: "#f57c00"
buttons:
      zip_url: https://github.com/batuhantrkgl/alrightlauncher/zipball/Latest
      zip_title: Zip Olarak İndir!
      zip_hide: false
      tar_hide: true
      github_hide: false # hides "View on Github"
