remote_theme: tuur29/pages-themes-cayman
title: Alright Launcher Website
description: Alright Launcher İçin Batuhan Türkoğlunun Geliştirdiği Website
darkmode: true 
syntax_theme: ./syntax.css # Leave empty for default, otherwise link to a pygments stylesheet
logo_url: ./logo.png # Either absolute or relative url
colors:
    gradient_left: "#155799"
    gradient_right: "#159957"
    header: "#fff"
    android_theme: "#000" # this default to gradient_color
    link: "#1e6bb8" # this default to gradient_color
    section_title: "#155799" # this default to gradient_color
buttons:
      zip_url: http://example.com/
      zip_title: Title
      zip_hide: true
      tar_url: http://example.com/
      tar_title: Title
      tar_hide: true
      github_hide: true # hides "View on Github"
